[package]
name = "substrate-client-keystore"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
parking_lot = "0.10.0"
async-trait = "0.1.30"
hex = "0.4"
serde_json = "1.0"

[dependencies.sp-core]
default-features = false
package = "sp-core"
git = "https://github.com/paritytech/substrate.git"
rev = "a208da16"

[dependencies.sp-keystore]
git = "https://github.com/paritytech/substrate.git"
rev = "a208da16"
package = "sp-keystore"

[dependencies.sc-keystore]
git = "https://github.com/paritytech/substrate.git"
rev = "a208da16"
package = "sc-keystore"

[dependencies.sp-keyring]
git = "https://github.com/paritytech/substrate.git"
rev = "a208da16"
package = "sp-keyring"

[dependencies.sp-application-crypto]
git = "https://github.com/paritytech/substrate.git"
rev = "a208da16"
package = "sp-application-crypto"

